networks:
  network-1:
    name: network-1

services:
  nginx:
    container_name: nginx-otus
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/public_html
    networks:
      - network-1
    depends_on:
      - phpfpm
      - mysql
  phpfpm:
    container_name: phpfpm-otus
    build: ./docker/images/php
    volumes:
      - ./app:/var/www/public_html
    networks:
      - network-1
    depends_on:
      - mysql
  mysql:
    container_name: mysql-otus
    image: mysql
    volumes:
      - ./docker/mysql/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: mysqld --user=root --sql-mode=""
    networks:
      - network-1
  redis:
    build: ./docker/images/redis
    container_name: redis-otus
    volumes:
      - ./docker/redis:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - network-1
  memcached:
    build: ./docker/images/memcached
    container_name: memcached-otus
    networks:
      - network-1